### ISSUE TITLE
Change notification error message that is shown after trying to update the status of a proposal

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#1273]
- [x] Change english version to: "To change the status into [NEW STATUS], make sure to complete all the mandatory fields, marked in red."
- [x] Change portuguese version to: "Para alterar o status para [NEW STATUS], preencha todos os campos obrigatórios, marcados em vermelho."

The error message to change is in the following screenshot: 

<img width="1440" alt="screen shot 2018-07-03 at 7 11 50 pm" src="https://user-images.githubusercontent.com/5572598/42247208-106379c2-7ef6-11e8-8b95-348d33117abd.png">

**Comment by cdparra** [comment]
@jamesholston there were two different issues that requested this change. I unified them into this issue. 

This change presents a problem: the list of `items` is defined as a configuration in the backend, which, in order to work, must coincide with the actual names of the fields of the contribution table in our database. This means that what we have in the database is the following: 

`appcivist.campaign.contribution.public_draft.status-requirements` =	`text,theme,keyword,Campus Proposta`

Therefore, when the backend responds to the UI saying that the requirement was not met, it will send the list of fields that were missing (this is why your message contains [description], because at that time the configuration was wrongly stored as follow: 

`appcivist.campaign.contribution.public_draft.status-requirements` =	`description,theme,keyword,Campus Proposta`

I propose a message along the following line to make it more generic. 

"To change the status of a proposal into [DESIRED_STATUS], you must provide all the required information. Check for the fields marked with an * and make sure they have some content before you change the status again."  

Then we just need to make sure to mark required things with an * in the page to show what is requried. 

Otherwise we will have to translate also each different field and it would make it complicated.

**Comment by jamesholston** [comment]
I assume that "text" in the backend config refers to "Summary".  Correct?  The problem with your proposed solution is that we would have to mark these fields (text, theme, keyword, and campus proposta) with an * from the beginning, even when the proposal is in private status mode.  That would lead users to think that these fields are required from the beginning.  We decided that they would not be necessary to develop a draft in private, but only to turn it public.  Thus the specified fields are only required to alter the status.  I don't see why it's complicated to translate four fields: resumo, tema, palavras-chave, campus proposta.  But maybe it will be for the future because in phase 3 we will have the same issue.  Thematic Proposals will can remain private for up to 4 weeks.  Then they must become public.  There will probably be additional required fields.  Is there anyway to have the * appear when the status button is changed?  Or to have the required fields names that are empty turn red to indicate that they are required?

**Comment by cdparra** [comment]
Maybe the best option would be to only mark the required fields when the user attempts to update, the backend rejects the attempt and then we mark the required fields. I think this is visible. If you agree, I will update the description of the issue to reflect this. 

text => is summary yes

**Comment by jamesholston** [comment]
Yes, I agree. When the user attempts to update, the backend rejects the attempt if any one of the required fields is empty.  It then marks the required fields.  Some questions:
-- Should we mark all the required fields or only the empty ones?  I would suggest only the empty.
-- How to mark them?  I would say to mark the field name in red, rather than use a small asterisk (*).
-- We should also return an error message.  If we mark the empty field name in red, then use:  "Para alterar o status para Público ou Publicada, preencha todos os campos obrigatórios, marcados em vermelho." 
If we use an asterisk:  "Para alterar o status para Público ou Publicada, preencha todos os campos obrigatórios, marcados com asterisco (*)."

**Comment by cdparra** [comment]
Ok, I have updated the issue accordingly now and will add another issue to cover the marking of mandatory fields in red when they are not filled.

**Comment by cdparra** [comment]
Translations were missing. Just added them.
