### ISSUE TITLE
Plan for Notifications v2 issues

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-pb-client#741]
[Notifications v2.pdf](https://github.com/socialappslab/appcivist-pb-client/files/1093728/Notifications.v2.pdf)

**Comment by cdparra** [comment]
[Notifications v3.pdf](https://github.com/socialappslab/appcivist-pb-client/files/1123019/Notifications.v3.pdf)

**Comment by rafaelangarita** [comment]
I saw that you have Facebook Messenger and Twitter Direct Messages, but I remember @cdparra  said were going to start only with Messenger. I think it was a good idea to include only Facebook Messenger at first to experience with this.

Also, Facebook is changing APIs and improving the Facebook Messenger platform for developers. Unfortunately, Messenger is a different system than Facebook, so Facebook user's id are not the same in Messenger, so there is no easy way for users to tell us who they are in Messenger. 
Two of the methods to link Messenger users to users in a particular system are:

- Account linking from Messenger: when users start a conversation with the Facebook Messenger bot for the first time, they are asked to log in into AppCivist to link accounts.
-  Account linking from AppCivist: instead of having users filling out their Facebook ids, they will check a "send-to-messenger" box or click a button. [The checkbox seems better suited for what we want](https://developers.facebook.com/docs/messenger-platform/plugin-reference/checkbox-plugin).


I think that we can start just by including the checkbox in the notifications settings page.

**Comment by cdparra** [comment]
@rafaelangarita I agree that we should start with Facebook messenger. Twitter can be grayed out until it is available. 

**About account linking:** probably  better to do it from Facebook as users will not visit their settings page much. It is better to have the call to action in the context where the action happens. How would this work with a bot?

**Comment by rafaelangarita** [comment]
@cdparra maybe we should "advertise" the bot as much as possible? 

You  can have the checkbox in the settings page (or whenever you'd like user to subscribe to notifications):
![screen shot 2017-07-06 at 10 17 55](https://user-images.githubusercontent.com/19403998/27902095-bc9e822a-6234-11e7-9e28-c737b3dd9155.png)

Use the other plugins whenever you'd like such as "send to messenger" or "message us"

![screen shot 2017-07-06 at 10 18 10](https://user-images.githubusercontent.com/19403998/27902146-fa129c90-6234-11e7-9918-5f4a188776dd.png)
![screen shot 2017-07-06 at 10 18 28](https://user-images.githubusercontent.com/19403998/27902148-fa28d3b6-6234-11e7-999d-148ad21a320e.png)

In the US, you have a paid option to directly [contact people if you have their phone number.](https://developers.facebook.com/docs/messenger-platform/guides/customer-matching)

Of course, they can also discover the bot in Facebook or in Messenger.
